/** @type {typeof import("../helpers/enums.js")} */
const { createReverseLookupObject } = requireBinding("shared/helpers/enums.js");

// When changing, update types/shared/index.d.ts aswell
alt.Enums.BlipColor = createReverseLookupObject({
    WHITE: 0,
    RED: 1,
    GREEN: 2,
    BLUE: 3,
    YELLOW: 5,
    LIGHT_RED: 6,
    VIOLET: 7,
    PINK: 8,
    LIGHT_ORANGE: 9,
    LIGHT_BROWN: 10,
    LIGHT_GREEN: 11,
    LIGHT_BLUE: 12,
    LIGHT_PURPLE: 13,
    DARK_PURPLE: 14,
    CYAN: 15,
    LIGHT_YELLOW: 16,
    ORGANE: 17,
    DARK_PINK: 19,
    GRANITE_GREEN: 20,
    DARK_BROWN: 21,
    LIGHT_GRAY: 22,
    LIGHT_PINK: 23,
    LEMON_GREEN: 24,
    FOREST_GREEN: 25,
    ELECTRIC_BLUE: 26,
    BRIGHT_PURPLE: 27,
    DARK_YELLOW: 28,
    DARK_CYAN: 30,
    BEIGE: 36,
    DARK_GRAY: 40,
    PINK_RED: 41,
    GOLD: 46,
    ORANGE: 47,
    BRILLIANT_ROSE: 48,
    MEDIUM_PURPLE: 50,
    SALMON: 51,
    DARK_GREEN: 52,
    BLIZZARD_BLUE: 53,
    ORACLE_BLUE: 54,
    SILVER: 55,
    EAST_BAY: 58,
    YELLOW_ORANGE: 60,
    MULBERRY_PINK: 61,
    ALTO_GRAY: 62,
    JELLY_BEAN_BLUE: 63,
    DARK_ORANGE: 64,
    MAMBA: 65,
    TRANSPARENT_BLACK: 72,
    DEEP_RED: 76,
    TRANSPARENT_RED: 79,
    TRANSPARENT_BLUE: 80,
    PURPLE: 83
});
