// When changing, update types/shared/index.d.ts aswell
alt.Enums.BlipColor = Object.freeze({
    White,
    Red,
    Green,
    Blue,
    Yellow: 5,
    LightRed,
    Violet,
    Pink,
    LightOrange,
    LightBrown,
    LightGreen,
    LightBlue,
    LightPurple,
    DarkPurple,
    Cyan,
    LightYellow,
    Organe,
    DarkPink: 19,
    GraniteGreen,
    DarkBrown,
    LightGray,
    LightPink,
    LemonGreen,
    ForestGreen,
    ElectricBlue,
    BrightPurple,
    DarkYellow,
    DarkCyan: 30,
    Beige: 36,
    DarkGray: 40,
    PinkRed,
    Gold: 46,
    Orange,
    BrilliantRose,
    MediumPurple: 50,
    Salmon,
    DarkGreen,
    BlizzardBlue,
    OracleBlue,
    Silver,
    EastBay: 58,
    YellowOrange: 60,
    MulberryPink,
    AltoGray,
    JellyBeanBlue,
    DarkOrange,
    Mamba,
    TransparentBlack: 72,
    DeepRed: 76,
    TransparentRed: 79,
    TransparentBlue: 80,
    Purple: 83
});
